# Generated by Django 5.1.15 on 2026-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('engine', models.CharField(choices=[('shift_rotation', 'Rotacion de turno')], default='shift_rotation', help_text='Motor de asignacion', max_length=30)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuracion estructurada del motor de asignacion')),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Prioridad de aplicacion (menor = se aplica primero)')),
                ('scope_records', models.JSONField(blank=True, default=list, help_text='IDs de registros del scope de planificacion a los que aplica. Vacio = aplica a todos.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de asignacion',
                'verbose_name_plural': 'Reglas de asignacion',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
