# Generated by Django 5.1.15 on 2026-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentrule',
            name='engine',
        ),
        migrations.AlterField(
            model_name='assignmentrule',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuracion: conditionField, conditionValue, overrideField, pattern, frequencyField/frequencyValue'),
        ),
    ]
