# Generated by Django 5.1.15 on 2026-07-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencerequest',
            name='indefinite',
            field=models.BooleanField(default=False, help_text='Ausencia sin fecha de fin conocida. Mientras esté activa (sin end_date), el empleado no se planifica.'),
        ),
        migrations.AlterField(
            model_name='absencerequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
