# Generated by Django 5.1.15 on 2026-08-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0004_dedupe_baja_medica'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencerequest',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
