# Generated by Django 5.1.15 on 2026-05-14 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0005_add_parent_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='0 = Lunes, 6 = Domingo (coincide con Python weekday())')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_days', to='shifts.shift')),
            ],
            options={
                'verbose_name': 'Día de turno',
                'verbose_name_plural': 'Días de turno',
                'ordering': ['shift', 'weekday'],
                'unique_together': {('shift', 'weekday')},
            },
        ),
    ]
