# Generated by Django 5.1.15 on 2026-05-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerpreference',
            name='shift_type',
            field=models.CharField(help_text='Code from catalog kind "shift_slot"', max_length=50),
        ),
    ]
