# Generated by Django 5.1.15 on 2026-05-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#628db4', max_length=20)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('start_time', models.TimeField(help_text='Hora de inicio del turno')),
                ('end_time', models.TimeField(help_text='Hora de fin del turno')),
                ('active', models.BooleanField(default=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['name'],
            },
        ),
    ]
