# Generated by Django 5.1.15 on 2026-05-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_update_target_entity_refs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='active',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='icon',
        ),
    ]
