# Generated by Django 5.1.15 on 2026-05-13 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_remove_color_icon_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['parent_id', 'name'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AddField(
            model_name='shift',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Turno padre. NULL = turno principal (columna del planificador).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shifts.shift'),
        ),
    ]
