# Generated by Django 5.1.15 on 2026-06-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_add_parent_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['name'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.RemoveField(
            model_name='shift',
            name='parent',
        ),
    ]
