# Generated by Django 5.1.15 on 2026-07-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_remove_parent_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Inicio de vigencia (inclusive). Vacío = sin límite inferior.', null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Fin de vigencia (inclusive). Vacío = sin límite superior.', null=True),
        ),
    ]
