# Generated by Django 5.1.15 on 2026-05-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Nombre de icono Material', max_length=50)),
                ('editable', models.BooleanField(default=True, help_text='Si es False los usuarios no pueden añadir ni eliminar valores')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de catalogo',
                'verbose_name_plural': 'Tipos de catalogo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KindAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Clave interna, ej: start_time', max_length=50)),
                ('label', models.CharField(help_text='Texto visible al usuario, ej: Hora inicio', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Numero'), ('time', 'Hora'), ('color', 'Color'), ('boolean', 'Si/No'), ('textarea', 'Texto largo')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=500)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.kind')),
            ],
            options={
                'verbose_name': 'Atributo de tipo',
                'verbose_name_plural': 'Atributos de tipo',
                'ordering': ['order'],
                'unique_together': {('kind', 'key')},
            },
        ),
        migrations.CreateModel(
            name='KindValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, help_text='Color CSS, ej: #FF0000', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.kind')),
            ],
            options={
                'verbose_name': 'Valor de catalogo',
                'verbose_name_plural': 'Valores de catalogo',
                'ordering': ['order', 'label'],
                'unique_together': {('kind', 'code')},
            },
        ),
        migrations.CreateModel(
            name='KindValueAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=500)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.kindattribute')),
                ('kind_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.kindvalue')),
            ],
            options={
                'verbose_name': 'Valor de atributo',
                'verbose_name_plural': 'Valores de atributo',
                'unique_together': {('kind_value', 'attribute')},
            },
        ),
    ]
