# Generated by Django 5.1.15 on 2026-08-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindattribute',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Numero'), ('float', 'Decimal'), ('time', 'Hora'), ('color', 'Color'), ('boolean', 'Si/No'), ('textarea', 'Texto largo')], default='text', max_length=20),
        ),
    ]
