# Generated by Django 5.1.15 on 2026-05-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_days', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Dia de descanso',
                'verbose_name_plural': 'Dias de descanso',
                'ordering': ['date'],
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
