# Generated by Django 5.1.15 on 2026-05-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='category', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('show_in_sidebar', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System entities cannot be deleted and are always present in the sidebar')),
                ('display_field', models.CharField(default='name', help_text='Clave del campo de data que se usa como etiqueta en selectores y tablas (ej: name, nombre, codigo)', max_length=50)),
                ('use_as_filter', models.BooleanField(default=False, help_text='Si es True, esta entidad aparece como filtro en el dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de entidad',
                'verbose_name_plural': 'Tipos de entidad',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EntityField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Numero'), ('boolean', 'Si/No'), ('color', 'Color'), ('time', 'Hora'), ('select', 'Seleccion'), ('textarea', 'Texto largo'), ('catalog_select', 'Seleccion de catalogo'), ('multi_catalog_select', 'Seleccion multiple de catalogo'), ('entity_select', 'Seleccion de entidad'), ('multi_entity_select', 'Seleccion multiple de entidad')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=200)),
                ('placeholder', models.CharField(blank=True, max_length=100)),
                ('options', models.JSONField(blank=True, default=list, help_text='Opciones para campo tipo select: ["opcion1", "opcion2"]')),
                ('kind_code', models.CharField(blank=True, help_text='Codigo del Kind del catalogo para campos catalog_select / multi_catalog_select', max_length=50)),
                ('target_entity', models.CharField(blank=True, help_text='Slug del EntityType relacionado para campos entity_select / multi_entity_select', max_length=50)),
                ('show_in_list', models.BooleanField(default=False, help_text='Mostrar como columna en la tabla del cliente')),
                ('allow_priority', models.BooleanField(default=False, help_text='Permite asignar prioridad/preferencia a cada seleccion (para campos multi-seleccion)')),
                ('help_text', models.CharField(blank=True, help_text='Texto de ayuda mostrado al usuario bajo el campo', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campo dinamico',
                'verbose_name_plural': 'Campos dinamicos',
                'ordering': ['entity_type', 'order', 'label'],
                'unique_together': {('entity_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='EntityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dynamic_fields.entitytype', to_field='slug')),
            ],
            options={
                'verbose_name': 'Registro de entidad',
                'verbose_name_plural': 'Registros de entidad',
                'ordering': ['id'],
            },
        ),
    ]
