# Generated by Django 5.1.15 on 2026-05-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityfield',
            name='display_key',
            field=models.CharField(blank=True, help_text='Campo del entity relacionado a mostrar en la tabla (si vacio, usa display_field del EntityType)', max_length=50),
        ),
    ]
