# Generated by Django 5.1.15 on 2026-05-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_fields', '0002_entityfield_display_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityfield',
            name='depends_on',
            field=models.CharField(blank=True, help_text='Clave del campo del que depende (en la misma entidad). Filtra las opciones automaticamente.', max_length=50),
        ),
        migrations.AddField(
            model_name='entityfield',
            name='depends_on_field',
            field=models.CharField(blank=True, help_text='Clave en el data del target_entity que debe coincidir con el valor del campo depends_on.', max_length=50),
        ),
    ]
