# Generated by Django 5.1.15 on 2026-05-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_fields', '0003_entityfield_depends_on_entityfield_depends_on_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitytype',
            name='is_planning_scope',
            field=models.BooleanField(default=False, help_text='Si es True, los registros de esta entidad son el "ámbito" de la planificación (turno + entidad). Solo una entidad debería tenerlo activo.'),
        ),
    ]
