# Generated by Django 5.1.15 on 2026-06-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_fields', '0006_create_system_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityfield',
            name='visible_when_field',
            field=models.CharField(blank=True, help_text='Clave del campo (misma entidad) que controla la visibilidad de este campo.', max_length=50),
        ),
        migrations.AddField(
            model_name='entityfield',
            name='visible_when_value',
            field=models.CharField(blank=True, help_text='Valor que debe tener visible_when_field para que este campo sea visible. Para boolean usar "true"/"false".', max_length=200),
        ),
    ]
