# Generated by Django 5.1.15 on 2026-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_fields', '0007_add_visible_when_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityfield',
            name='generator_role',
            field=models.CharField(blank=True, choices=[('', 'Sin rol especial'), ('shift_assignment', 'Turno asignado (turno principal del worker)'), ('rotation_flag', 'Indicador de rotación (boolean)'), ('secondary_shift', 'Turno secundario (rotación)'), ('rotation_frequency', 'Frecuencia de rotación en semanas (número)')], help_text='Rol que juega este campo en la generación automática del planificador.', max_length=50),
        ),
    ]
