# Generated by Django 5.1.15 on 2026-06-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_fields', '0008_add_generator_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityfield',
            name='generator_role',
        ),
    ]
