# Generated by Django 5.1.15 on 2026-06-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_fields', '0009_remove_generator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityfield',
            name='show_as_filter',
            field=models.BooleanField(default=False, help_text='Mostrar como desplegable de filtro en la vista de registros'),
        ),
    ]
