# Generated by Django 5.1.15 on 2026-07-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_fields', '0012_worker_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Numero'), ('boolean', 'Si/No'), ('color', 'Color'), ('time', 'Hora'), ('select', 'Seleccion'), ('textarea', 'Texto largo'), ('catalog_select', 'Seleccion de catalogo'), ('multi_catalog_select', 'Seleccion multiple de catalogo'), ('entity_select', 'Seleccion de entidad'), ('multi_entity_select', 'Seleccion multiple de entidad'), ('icon', 'Icono')], max_length=20),
        ),
    ]
