# Generated by Django 5.1.15 on 2026-08-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_fields', '0016_alter_entityfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityfield',
            name='allow_unassigned_filter',
            field=models.BooleanField(default=False, help_text='Anade la opcion "Sin asignar" al filtro de este campo, para localizar los registros que no tienen ningun valor. Es por campo, no global.'),
        ),
    ]
