# Generated by Django 5.1.15 on 2026-05-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Planificador de Turnos', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, help_text='Logo de la empresa (PNG/SVG recomendado, fondo transparente)', null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, help_text='Icono de la pestana del navegador (32x32 px)', null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#EF4444', help_text='Color principal (hex, ej: #EF4444)', max_length=20)),
                ('primary_dark', models.CharField(default='#B91C1C', help_text='Variante oscura del color principal', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de marca',
                'verbose_name_plural': 'Configuracion de marca',
            },
        ),
    ]
