# Generated by Django 5.1.15 on 2026-08-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='date_picker_mode',
            field=models.CharField(choices=[('week', 'Por semanas'), ('range', 'Por rango de fechas')], default='range', help_text='Por semanas: al pulsar un dia se selecciona su semana completa. Por rango: el usuario elige fecha de inicio y de fin.', max_length=10),
        ),
    ]
