# Generated by Django 5.1.15 on 2026-05-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('engine', models.CharField(choices=[('count', 'Conteo'), ('exclusion', 'Exclusion'), ('match', 'Coincidencia')], default='count', help_text='Motor de evaluacion de la restriccion', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuracion estructurada del motor')),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Aviso')], default='error', max_length=10)),
                ('message', models.CharField(blank=True, default='', help_text='Mensaje personalizado. Placeholders: {worker}, {count}, {limit}, {area}, {shift}, {role}, {worker1}, {worker2}', max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restriccion',
                'verbose_name_plural': 'Restricciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='planning.weeklyplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestrictionViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], max_length=10)),
                ('day_date', models.DateField(null=True)),
                ('shift_type', models.CharField(max_length=10, null=True)),
                ('restriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restrictions.restriction')),
                ('validation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='restrictions.validationresult')),
            ],
            options={
                'ordering': ['day_date', 'shift_type'],
            },
        ),
    ]
