# Generated by Django 5.1.15 on 2026-05-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrictions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restriction',
            name='engine',
            field=models.CharField(choices=[('count', 'Conteo'), ('exclusion', 'Exclusion'), ('match', 'Coincidencia'), ('condition', 'Condición')], default='count', help_text='Motor de evaluacion de la restriccion', max_length=20),
        ),
    ]
