# Generated by Django 5.1.15 on 2026-05-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrictions', '0002_add_condition_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='restriction',
            name='scope_records',
            field=models.JSONField(blank=True, default=list, help_text='IDs de registros del scope de planificacion a los que aplica. Vacio = aplica a todos.'),
        ),
    ]
