# Generated by Django 5.1.15 on 2026-07-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrictions', '0003_add_scope_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restriction',
            name='engine',
            field=models.CharField(choices=[('count', 'Conteo'), ('exclusion', 'Exclusion'), ('match', 'Coincidencia'), ('condition', 'Condición'), ('closed_day', 'Día de cierre')], default='count', help_text='Motor de evaluacion de la restriccion', max_length=20),
        ),
    ]
