# Generated by Django 5.1.15 on 2026-05-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('day_name', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan diario',
                'verbose_name_plural': 'Planes diarios',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True)),
                ('plan_json', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan semanal',
                'verbose_name_plural': 'Planes semanales',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
            options={
                'verbose_name': 'Asignacion de turno',
                'verbose_name_plural': 'Asignaciones de turno',
            },
        ),
        migrations.CreateModel(
            name='DayPlanShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(help_text='Code from catalog kind "shift_slot"', max_length=20)),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='planning.dayplan')),
                ('shift_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.shiftassignment')),
            ],
            options={
                'unique_together': {('day_plan', 'shift_type', 'shift_assignment')},
            },
        ),
        migrations.CreateModel(
            name='AreaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_record_id', models.PositiveIntegerField(help_text='EntityRecord ID of the area')),
                ('shift_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='planning.shiftassignment')),
            ],
            options={
                'verbose_name': 'Asignacion de area',
                'verbose_name_plural': 'Asignaciones de area',
                'unique_together': {('shift_assignment', 'area_record_id')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_order', models.IntegerField()),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.dayplan')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='planning.weeklyplan')),
            ],
            options={
                'ordering': ['day_order'],
                'unique_together': {('weekly_plan', 'day_order')},
            },
        ),
    ]
