# Generated by Django 5.1.15 on 2026-05-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='scope_entity_id',
            field=models.IntegerField(default=0, help_text='EntityRecord ID del ámbito de planificación (0 = sin ámbito / legado)'),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyplan',
            unique_together={('start_date', 'scope_entity_id')},
        ),
    ]
