# Generated by Django 5.1.15 on 2026-07-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_add_scope_entity_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scope_entity_id', models.IntegerField(default=0, help_text='EntityRecord ID del ámbito al que aplica el cierre (0 = todos)')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Día de cierre',
                'verbose_name_plural': 'Días de cierre',
                'ordering': ['date'],
                'unique_together': {('date', 'scope_entity_id')},
            },
        ),
    ]
